workflows:
  android-apk-build:
    name: Build AppVault APK
    environment:
      java: 17
    scripts:
      - name: Unzip project
        script: unzip AppVault.zip
      - name: Build Debug APK
        script: |
          cd AppVault
          gradle assembleDebug
    artifacts:
      - AppVault/app/build/outputs/apk/debug/**/*.apk
